services:
  usermanager_api:
    build: .
    container_name: usermanagerapi
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - mongo_data:/data/db
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb_service
    command: air

  mongodb_service:
    container_name: mongodb_service
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
